INSERT INTO dishes (name, type) VALUES
  ('Caldo de pollo', 'BREAKFAST'),
  ('Chilaquiles rojos c/huevo estrellado', 'BREAKFAST'),
  ('Huevos rancheros', 'BREAKFAST'),
  ('Chimichangas de frijol c/queso y chorizo', 'BREAKFAST'),
  ('Huevo con jamón y ejotes', 'BREAKFAST'),
  ('Papas c/chorizo y queso', 'BREAKFAST'),
  ('Pollo en crema de chipotle', 'BREAKFAST'),
  ('Pambazos de papas c/chorizo', 'BREAKFAST'),
  ('Fajitas de pollo', 'BREAKFAST'),
  ('Enchiladas rojas de pierna', 'BREAKFAST'),
  ('Tinga de molida', 'LUNCH'),
  ('Albóndigas en chipotle c/papas', 'LUNCH'),
  ('Milanesa de res', 'LUNCH'),
  ('Tortas de carnitas', 'LUNCH'),
  ('Tamales verdes y rojos de pollo', 'LUNCH'),
  ('Flautas de pollo', 'LUNCH'),
  ('Tacos de camarón', 'LUNCH'),
  ('Rajas c/elote y pollo', 'LUNCH'),
  ('Pollo a la plancha enchilado', 'LUNCH'),
  ('Costilla en salsa verde', 'LUNCH'),
  ('Arroz rojo c/elote', 'COMPLEMENT'),
  ('Frijoles c/chicharrón', 'COMPLEMENT'),
  ('Ensalada de espagueti', 'COMPLEMENT'),
  ('Arroz blanco c/cebollín', 'COMPLEMENT'),
  ('Puré de papa', 'COMPLEMENT'),
  ('Codito a la boloñesa', 'COMPLEMENT'),
  ('Arroz al curry c/chícharo', 'COMPLEMENT'),
  ('Frijoles charros', 'COMPLEMENT'),
  ('Coditos c/crema y elote', 'COMPLEMENT'),
  ('Frijoles puercos', 'COMPLEMENT'),
  ('Caldo de papa', 'CONSOMME'),
  ('Caldo de camarón', 'CONSOMME'),
  ('Sopa de fideos', 'CONSOMME'),
  ('Lentejas preparadas', 'CONSOMME'),
  ('Consomé de res', 'CONSOMME'),
  ('Arroz c/leche', 'DESSERT'),
  ('Gelatina de mosaico', 'DESSERT'),
  ('Fruta', 'DESSERT'),
  ('Chocoflan', 'DESSERT'),
  ('Postre de leche', 'DESSERT');